name: Generate TOC on PR Merge

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event.pull_request.merged == true && github.base_ref == 'main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run TOC generation script
        run: |
          chmod +x generate_toc_for_readme.sh
          ./generate_toc_for_readme.sh
